export const LOGIN_USER = 'LOGIN_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_TRACK_ID_TO_UPLOADS = 'ADD_TRACK_ID_TO_UPLOADS';

export const ADD_FAV_TRACK = 'ADD_FAV_TRACK';

export const REMOVE_FAV_TRACK = 'REMOVE_FAV_TRACK';
